---
title: "Untitled"
author: "Ruoyuan Qian"
date: "11/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(ggplot2)
library(ggridges)

knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

# Problem 1
```{r}
set.seed(10)
iris_with_missing = iris %>%
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

# Problem 2
```{r}

fill_na = function(x) {
  
  if (is.numeric(x)) {
    replace = round((mean(x, na.rm = TRUE)),2)
    x[is.na(x)] <- replace
  } else if (is.character(x)) {
    replace = "virginica"
    x[is.na(x)] <- replace
  }
  x
}

iris_with_missing_fill = map(iris_with_missing,fill_na)  
 
  filled_data = as.data.frame(iris_with_missing_fill)
  
```


     pivot_longer(
       week_1:week_8,
       names_to = "week",
       names_prefix = "week_",
       values_to = "observation")
       
```{r}
name = list.files(path="./data",data("csv"))

 read_data = function(x){
   file_name = str_c("./data/",x)
   read_csv(file_name) %>% 
     mutate(id = str_sub(x,5,6),
            id = as.numeric(id),
            arm = str_sub(x,1,3))
                        }
```

```{r}

result_list = map(name,read_data)

result_data = 
  tibble(
    name =  name,
    result = result_list)%>% 
  janitor::clean_names()%>%
  unnest(result) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "observation") %>% 
  mutate(id = str_sub(name,5,6),
         id = as.numeric(id),
         arm = str_sub(name,1,3),
         week = as.numeric(week)) %>% 
  select(id,arm,everything()) %>% 
  select(-name)

  
 
```

```{r}
result_data %>% 
  group_by(arm,id) %>% 
ggplot(aes(y = observation, 
           x = week, color = factor(id)))+
  geom_line()+
  facet_grid(. ~ arm) +
  theme(legend.position = "bottom")+
  labs(x = "Week",
       y = "Observation",
       title = "Plot 1   Spaghetti plot showing observations on each subject over time"
       )
```

